version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: real_world_dev
          POSTGRES_HOST_AUTH_METHODL: trust


    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: echo 0.0.0.0 dbhost | sudo tee -a /etc/hosts

      - run:
          name: wait for Postgres
          command: dockerize -wait tcp://dbhost:5432 -timeout 2m

      - run:
          name: pre tests
          command: |
            echo 0.0.0.0 dbhost | sudo tee -a /etc/hosts
            sudo apt-get install -y postgresql-client
            make db_reset

      - run:
          name: tests
          command: |
            go test ./org
            go test ./blog

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
